#:schema node_modules/wrangler/config-schema.json
name = "onlineteleprompt-dot-com"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Custom domain routing
[[routes]]
pattern = "teleprompter24.com"
custom_domain = true

[[routes]]
pattern = "www.teleprompter24.com"
custom_domain = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "onlineteleprompt-db"
database_id = "a4acf907-f82f-411a-8b20-feecde86e3fc"
