#:schema node_modules/wrangler/config-schema.json
name = "onlineteleprompt-dot-com"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "onlineteleprompt-db"
database_id = "a4acf907-f82f-411a-8b20-feecde86e3fc"
preview_database_id = "DB"
